FROM golang:alpine AS build
LABEL maintainer "Albert Shin <shina2@rpi.edu>"

WORKDIR ${GOPATH}/src/github.com/albshin/tutescrew

COPY . .

RUN go build -o tutescrew ./cmd/tutescrew

FROM alpine
LABEL maintainer "Albert Shin <shina2@rpi.edu>"

WORKDIR /app

COPY --from=build go/src/github.com/albshin/tutescrew/tutescrew .
COPY --from=build go/src/github.com/albshin/tutescrew/config.json ./config.json 

EXPOSE 8080

CMD [ "./tutescrew" ]